### ISSUE TITLE
工作原理时间描述错误

### ISSUE THREAD

**Issue by qywk99** [devsapp/keep-warm-fc#3]
cronExpression 请求的频率(默认2分钟)
工作原理中请求频率的配图以及描述信息为2秒钟，正确描述应该为2分钟。

**Comment by wss-git** [comment]
可以贴一个链接吗？

**Comment by qywk99** [comment]
https://github.com/devsapp/keep-warm-fc/blob/master/readme.md
![image](https://user-images.githubusercontent.com/45910487/176574012-c8e350fb-1934-49a0-aff6-a461220b3822.png)

**Comment by heimanba** [comment]
感谢，已修复哈

**Comment by qywk99** [comment]
修复了，但没完全修复






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [devsapp/keep-warm-fc] 工作原理时间描述错误 (Issue #3)





 
感谢，已修复哈
